In [15]:
import numpy as np
np.set_printoptions(precision=3, suppress=True, threshold=10000)
from scipy import linalg

In [53]:
# x = np.arange(15)
# x = x * (-1) ** x
# A = np.stack(np.split(x, 3), 1) + 1
# A
np.random.seed(10)
A = 10 * np.random.randn(4, 6)

Q, R = linalg.qr(A, mode='economic')

In [54]:
R

array([[-22.313,   7.234,  23.364,  13.782, -10.909, -12.417],
       [  0.   , -14.911,   2.846,  -8.841,   1.177,  12.893],
       [  0.   ,   0.   ,   9.011,   6.586,   8.556, -11.471],
       [  0.   ,   0.   ,   0.   ,  -3.915,   0.166,  17.754]])

In [46]:
A1 = A[:3, :]
A2 = A[3:, :]
Q, R = linalg.qr(A1, mode='economic')
Q1, R1  = linalg.qr_insert(Q, R, A2, k=Q.shape[0])
R1

array([[21.921,  4.867],
       [ 0.   , 15.109]])

array([[480.547, 106.702],
       [106.702, 251.978]])